[package]
name = "lsm-tree"
description = "A K.I.S.S. implementation of log-structured merge trees (LSM-trees/LSMTs)"
license = "MIT OR Apache-2.0"
version = "1.0.2"
edition = "2021"
rust-version = "1.74.0"
readme = "README.md"
include = ["src/**/*", "LICENSE-APACHE", "LICENSE-MIT", "README.md"]
repository = "https://github.com/fjall-rs/lsm-tree"
homepage = "https://github.com/fjall-rs/lsm-tree"
keywords = ["database", "lsmt", "lsm", "rocksdb", "leveldb"]
categories = ["data-structures", "database-implementations", "algorithms"]

[lib]
name = "lsm_tree"
path = "src/lib.rs"

[features]
default = []
bloom = ["dep:seahash"]
segment_history = ["dep:serde", "dep:serde_json"]

[dependencies]
byteorder = "1.5.0"
crc32fast = "1.4.0"
crossbeam-skiplist = "0.1.3"
double-ended-peekable = "0.1.0"
log = "0.4.21"
lz4_flex = "0.11.3"
path-absolutize = "3.1.1"
quick_cache = { version = "0.5.1", default-features = false, features = [] }
seahash = { version = "4.1.0", optional = true }
self_cell = "1.0.4"
serde = { version = "1.0.200", features = ["derive", "rc"], optional = true }
serde_json = { version = "1.0.116", optional = true }
tempfile = "3.10.1"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
fs_extra = "1.3.0"
nanoid = "0.4.0"
test-log = "0.2.16"

[[bench]]
name = "lsmt"
harness = false
path = "benches/lsmt.rs"
required-features = ["bloom"]
