[package]
name = "lsm-tree"
description = "A K.I.S.S. implementation of log-structured merge trees (LSM-trees/LSMTs)"
license = "MIT OR Apache-2.0"
version = "2.0.0"
edition = "2021"
rust-version = "1.74.0"
readme = "README.md"
include = ["src/**/*", "LICENSE-APACHE", "LICENSE-MIT", "README.md"]
repository = "https://github.com/fjall-rs/lsm-tree"
homepage = "https://github.com/fjall-rs/lsm-tree"
keywords = ["database", "lsmt", "lsm", "rocksdb", "leveldb"]
categories = ["data-structures", "database-implementations", "algorithms"]

[lib]
name = "lsm_tree"
path = "src/lib.rs"

[features]
default = []
lz4 = ["dep:lz4_flex"]
miniz = ["dep:miniz_oxide"]
bloom = ["dep:seahash"]
all = ["bloom", "lz4", "miniz"]

[dependencies]
byteorder = "1.5.0"
crc32fast = "1.4.2"
crossbeam-skiplist = "0.1.3"
double-ended-peekable = "0.1.0"
enum_dispatch = "0.3.13"
guardian = "1.1.0"
log = "0.4.21"
lz4_flex = { version = "0.11.3", optional = true }
miniz_oxide = { version = "0.7.3", optional = true }
path-absolutize = "3.1.1"
quick_cache = { version = "0.6.0", default-features = false, features = [
  "ahash",
] }
seahash = { version = "4.1.0", optional = true }
self_cell = "1.0.4"
smallvec = { version = "1.13.2" }
tempfile = "3.10.1"
value-log = { path = "../value-log" }

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
fs_extra = "1.3.0"
nanoid = "0.4.0"
test-log = "0.2.16"

[package.metadata.cargo-all-features]
denylist = ["all"]

[[bench]]
name = "block"
harness = false
path = "benches/block.rs"
required-features = ["lz4", "miniz"]

[[bench]]
name = "bloom"
harness = false
path = "benches/bloom.rs"
required-features = ["bloom"]

[[bench]]
name = "tree"
harness = false
path = "benches/tree.rs"
required-features = ["lz4", "miniz"]

[[bench]]
name = "level_manifest"
harness = false
path = "benches/level_manifest.rs"
required-features = []

[[bench]]
name = "fd_table"
harness = false
path = "benches/fd_table.rs"
required-features = []
